[package]
name = "mine-imator"
description = "Mine-imator: 3D movie maker based on Minecraft"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "mine_imator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
mi-anim = { workspace = true }
mi-assets = { workspace = true }
mi-core = { workspace = true }
mi-format = { workspace = true }
mi-mesh = { workspace = true }
glam = "0.30"
mi-project = { workspace = true }
mi-render = { workspace = true }
pollster = "0.4"
serde = { workspace = true }
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-dialog = "2"
thiserror = { workspace = true }

